import React from 'react';
import Head from 'next/head';

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Your Amazing Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
        <h1 className="text-6xl font-bold">Welcome to Your Amazing Landing Page</h1>
        <p className="mt-4 text-xl">This is a placeholder for your amazing landing page content.</p>
      </main>

      <footer className="flex w-full items-end justify-center border-t border-gray-200 p-6">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <img src="/vercel.svg" alt="Vercel Logo" className="h-4 w-auto" />
        </a>
      </footer>
    </div>
  );
}
